apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - schedule-example.yaml
  - chaosengine.yaml
  - secrets.yaml
  - network-chaos.yaml
  - cpu-stress.yaml

configMapGenerator:
  - name: chaos-toolkit-configs
    namespace: weapon-system
    files:
      - pod-failure.yaml
      - steady-state-probe.yaml
