apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: death-star-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/organization/death-star.git'
    path: kubernetes/apps
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
